version: '2'
services:
  account:
    image: account-service
    restart: always
    ports:
      - 2222:2222
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  config:
    image: config-service
    restart: always
    ports:
      - 8081:8081
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  customer:
    image: customer-service
    restart: always
    ports:
      - 3333:3333
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  discovery:
    image: discovery-service
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  frontend:
    image: frontend-service
    restart: always
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  gateway:
    image: gateway-service
    restart: always
    ports:
      - 8765:8765
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  zipkin:
    image: zipkin-service
    restart: always
    ports:
      - 9411:9411
    logging:
      options:
        max-size: "10m"
        max-file: "10"